version: '3'
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: geocog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geocog-postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  minio:
    image: minio/minio:latest
    container_name: geocog-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - airflow_network

networks:
  airflow_network:
    external: false

volumes:
  postgres_data:
  minio_data: