artifacts_root: artifacts

data_ingestion:
  source_URL: https://earthquake.usgs.gov/fdsnws/event/1/query
  minio_endpoint: host.docker.internal:9000

storage:
  eq_raw_bucket_name: earthquake-raw
  eq_curated_bucket_name: earthquake-curated

postgres:
  conn_id: geocog_postgres_db
